# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fabiolima
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-framework-api

provider:
  name: aws
  runtime: python3.12
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: !Ref SNSTopic
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource: !GetAtt SQSQueue.Arn

functions:
  ${file(serverless/functions/hello.yml)}
  ${file(serverless/functions/apiHandler.yml)}

resources:
  - ${file(serverless/resources/sns.yml)}
  - ${file(serverless/resources/sqs.yml)}
