Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:service}-topic
      DisplayName: ${self:service} Topic
  
  SNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: sqs
      Endpoint: !GetAtt SQSQueue.Arn
